### ISSUE TITLE
Add OGB dataset

### ISSUE THREAD

**Issue by zsz00** [JuliaML/MLDatasets.jl#101]
The [OGB](https://ogb.stanford.edu/docs/dataset_overview/) datasets is an important graph benchmark database. 

The Open Graph Benchmark (OGB) aims to provide graph datasets that cover important graph machine learning tasks, diverse dataset scale, and rich domains.

Hope can join it here.

**Comment by yuehhua** [comment]
@zsz00 Hi! OGB datasets are currently provided in [GraphMLDatasets.jl](https://github.com/yuehhua/GraphMLDatasets.jl).
Currently, most dataset for node property prediction tasks are available, but some datasets containing heterogeneous graph are not available now. Datasets for link property prediction task are ongoing. When datasets are ready, I will move them here.

**Comment by CarloLucibello** [comment]
Closed in #106
