### ISSUE TITLE
Movielens datasets

### ISSUE THREAD

**Issue by matbesancon** [JuliaML/MLDatasets.jl#104]
The movielens recommendation matrices could be nice additions to MLDatasets

**Comment by CarloLucibello** [comment]
For reference, download links can be found here
https://grouplens.org/datasets/movielens/

**Comment by Dsantra92** [comment]
Needed for blogpost in [GraphNeuralNetworks.jl](https://github.com/CarloLucibello/GraphNeuralNetworks.jl/issues/173)
