### ISSUE TITLE
load torch tensors in OGBDatasets

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaML/MLDatasets.jl#107]
Some of the features of the OGBDataset are downloaded as torch tensor stored in the ".pt" format. They are currently ignored at the moment, but we could load them using Pickle.jl (e.g. see this [comment](https://github.com/FluxML/Metalhead.jl/issues/112#issuecomment-1074176899))

**Comment by Dsantra92** [comment]
Can I work on this?

**Comment by CarloLucibello** [comment]
Sure. I don't remember for which specific dataset this was needed though

**Comment by CarloLucibello** [comment]
This problem can be seen in `OGBDataset("ogbl-collab")`

**Comment by Dsantra92** [comment]
Been inactive due to Uni. exams, will start working on it today.

**Comment by yuehhua** [comment]
Some problems have been overcome here, including loading ".pt" format using Pickle.jl and have been discussed with @chengchingwen : https://github.com/yuehhua/GraphMLDatasets.jl/blob/65d6a2bb02d31569a64b47004a0c4b192739a066/src/preprocess.jl#L391
Hope these code help.
