### ISSUE TITLE
MPI Faust dataset

### ISSUE THREAD

**Issue by Dsantra92** [JuliaML/MLDatasets.jl#155]
Required for [GraphNeuralNetworks.jl #173](https://github.com/CarloLucibello/GraphNeuralNetworks.jl/issues/173)

[Download Link](http://faust.is.tue.mpg.de/challenge/Inter-subject_challenge/datasets). User needs to sign in before downloading the dataset.

**Comment by CarloLucibello** [comment]
Can you link the dataset?

**Comment by Dsantra92** [comment]
Done.
