### ISSUE TITLE
Issues on M1 due to use of BinaryProvider

### ISSUE THREAD

**Issue by f-ij** [JuliaML/MLDatasets.jl#159]
The package BinaryProvider is old and not well supported on the M1 platform, causing problems when installing this package.

**Comment by CarloLucibello** [comment]
We don't directly depend on BinaryProvider here, which imported package carries the dependence?

**Comment by f-ij** [comment]
It turns out to be [DataDeps](https://github.com/oxinabox/DataDeps.jl/issues/152)

**Comment by CarloLucibello** [comment]
The maintainer in https://github.com/oxinabox/DataDeps.jl/issues/152 seems to be willing to drop BinaryProvider by keeping only julia >= 1.6 compatibility. Would be willing to file a PR @f-ij ? otherwise I can do it when I find some time

**Comment by f-ij** [comment]
I'm quite new to this, so I wouldn't know exactly what to do. Would be great if you can find the time!

**Comment by Dsantra92** [comment]
Issue fixed with https://github.com/oxinabox/DataDeps.jl/pull/159?
