### ISSUE TITLE
Potential edge mismatch in TUDatasets?

### ISSUE THREAD

**Issue by Dsantra92** [JuliaML/MLDatasets.jl#197]
https://github.com/JuliaML/MLDatasets.jl/blob/b9a6f7141c604f1f86189540e0120a77670c3a95/src/datasets/graphs/tudataset.jl#L96-L98

should be
```julia
 source, target = source[p], target[p]
```
?

**Comment by CarloLucibello** [comment]
yes, definitely wrong
