### ISSUE TITLE
JuliaML

### ISSUE THREAD

**Issue by tbreloff** [JuliaML/MLDatasets.jl#2]
Hi @hshindo any interest in moving this package to JuliaML and/or collaborating with us?

**Comment by hshindo** [comment]
Yes, moving to JuliaML is fine.

**Comment by tbreloff** [comment]
Cool! (btw... there's absolutely no pressure here.  if you want to keep the repo here it's fine)

I was going to start putting something like this together... better to collaborate.

cc: @JuliaML

**Comment by hshindo** [comment]
Thanks.
If there's something I can do for you, please let me know!

**Comment by tbreloff** [comment]
You'll grant me any three wishes?? :wink: 

Would you like to be involved with JuliaML?  I haven't used Merlin, but I'm sure there are good ways to collaborate.

As for datasets, I'd love to get a audio/speech dataset easily available.  Any experience there?

**Comment by hshindo** [comment]
Yes, I'm happy to be involved with JuliaML.

Maybe MLDatasets.jl is a good start to collaborate with. For Merlin, this is still alpha-stage, so I want to keep it until it becomes mature. (collaboration is welcome)

My research field is mainly NLP, so I don't have much experience about speech and vision. That's why I'd love to collaborate with others.

**Comment by tbreloff** [comment]
@hshindo I invited you to JuliaML... looking forward to collaborating!

**Comment by hshindo** [comment]
@tbreloff I joined JuliaML, Thanks.

I have three options:
* Create a new MLDatasets.jl repo in JuliaML, and register to METADATA.
* Merge this with MLDataUtils.jl
* Fork this repo in JuliaML

Any thoughts?

**Comment by tbreloff** [comment]
Great!  I think the easiest is to just transfer your existing repo to JuliaML.  Settings --> Options --> Transfer Ownership.  There's no need to worry about registering in METADATA right away... most of JuliaML is unregistered at the moment.  Forking is not as ideal but if you really want to keep ownership we can make it work.

My thought is that we could possibly merge with dataset-packages that @ahwillia and @Evizero are working on, and that MLDataUtils could be a dependency and define a consistent interface for retrieving and loading the datasets.

Thoughts?

**Comment by hshindo** [comment]
OK, I transferred the repo right now.
README.md will be updated soon.

I understand. When the time comes, let's discuss about the unified dataset package for ML.
Until then, I'm going to maintain this repo and add more datasets.

**Comment by Evizero** [comment]
Hey, just wanted to mention that I got the ping and am still dwelling on this and how to best proceed/unify further down the road. Especially in terms of dataset license questions. I don't have an answer yet, but this package looks like a good start

**Comment by hshindo** [comment]
I see.
What exactly do you mean "dataset license questions"?
Currently, this repo focuses on *open* datasets.

**Comment by Evizero** [comment]
Open or not, credit must be given to the source in some appropriate way I think. especially if there are terms of use.

**Comment by Evizero** [comment]
Another aspect is that the package itself is MIT licensed, which allows for commercial use. I wouldn't be too confident that all datasets allow that too. A user needs to be made aware of that

**Comment by hshindo** [comment]
I see.
I'm not sure how to deal with the license issues, but this should be done properly.

**Comment by Evizero** [comment]
Me neither to be fair, but I will investigate once I got some time on my hands. The download-on-demand approach that you took seems the safest option either way. Maybe we can introduce some prompt that displays information about the dataset and requires the user to accept or something like that

**Comment by hshindo** [comment]
Thank you for your information. This is reasonable.
I'll think about the prompt.
PR and commit is of course always welcome.

Plus, please let us know if you have a good idea how to proceed/unify this repo into JuliaML.
