### ISSUE TITLE
OGBDataset ogbg-molhiv has wrong shape of edge features

### ISSUE THREAD

**Issue by chrisn-pik** [JuliaML/MLDatasets.jl#223]
Wrong dimension of edge features, there are 6 edge features, but 3 should be correct
```julia
using MLDatasets, DataFrames

data = OGBDataset("ogbg-molhiv")
size(data[1].graphs.edge_data.features)
```
returns
```julia
(6, 20)
```

However, 
```julia
data[1].graphs.num_edges
```

returns
```julia
40
```

I assume the correct size of the edge features would be ```(3,40)``` instead of ```(6,20)```

I am using DataFrames v1.6.1 and  MLDatasets v0.7.14

Using python and obg, the shape is (40,3):

```python
from ogb.graphproppred import PygGraphPropPredDataset
dataset = PygGraphPropPredDataset(name = "ogbg-molhiv", root = '.')
dataset[0].edge_attr.shape
torch.Size([40, 3])
```

and 
```python
dataset[0].edge_index.shape
torch.Size([2, 40])
```

**Comment by CarloLucibello** [comment]
it seems likely that the graph is undirected, and when converting it to a directed one we forgot to duplicate the edge features. Would you like to file a PR with a fix? I can give some indirections
