### ISSUE TITLE
Contributing synthetic datasets

### ISSUE THREAD

**Issue by xukai92** [JuliaML/MLDatasets.jl#29]
I'd like to contirbute 2 synthetic datasets to this package

The **2D ring** dataset
```julia
ring_dataset = RingDataset(10, 1.5, 0.1)
x = rand(ring_dataset, 1_000)
```
![download1](https://user-images.githubusercontent.com/5985769/72203698-e61a1900-3466-11ea-9528-428b766693f9.png)

Images generated from **independent features**
```julia
feature_dataset = FeatureDataset(get_features_griffiths2011())
x = rand(feature_dataset, 100)
```
![download2](https://user-images.githubusercontent.com/5985769/72203699-e9150980-3466-11ea-947f-eaa695adad46.png)

How could I proceed?

PS: I already implemented them in https://github.com/xukai92/MLToolkit.jl/blob/master/src/Datasets/Datasets.jl

**Comment by johnnychen94** [comment]
Oh, I think these two don't exactly meet the design of this package. All datasets in this package are downloaded from an external source. By saying this, as long as you follow the same interfaces, I think it's a good proposal already:

```julia
train_x, train_y = RingDataset.traindata()
test_x,  test_y  = RingDataset.testdata()
```

and since this is a generated random dataset, it's better to provide a default rng for that so the results are reproducible:

```julia
train_x, train_y = RingDataset.traindata([rng=Random.MersenneTwister(0)])
```

By the way, do you have a reference for these two datasets?

**Comment by xukai92** [comment]
Sounds good. I can adapt to the interface.

Regarding randomness, maybe it's better to deal with it during construction, i.e. `RingDataset([rng=GLOBAL_RNG], ...)`?

The references for independet features are in the source code. I need to figure out who uses the 2D ring first. If I cannot find the first one, I can certainly add some papers that use it.

**Comment by johnnychen94** [comment]
> Regarding randomness, maybe it's better to deal with it during construction, i.e. RingDataset([rng=GLOBAL_RNG], ...)?

Hmmm, actually all those datasets here are modules

**Comment by xukai92** [comment]
Oh I see your point. Yes I can do this, although it feels a bit weird now.

**Comment by xukai92** [comment]
Should I treat them as two individual modules or one module called Synthetic and add them there actually?

**Comment by johnnychen94** [comment]
I don't have any preference here, so I guess it's better to keep the same style(i.e., one module per dataset) unless you have specific reasons not to.
