### ISSUE TITLE
missing datasets from Flux

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaML/MLDatasets.jl#36]
This is a list of datasets that are available in Flux but not in MLDatasets. It would be useful to add them soon here, so that we can make MLDatasets' the default dataset provider for Flux.

- [x] Boston Housing
- [ ] CMU dictionary

**Comment by johnnychen94** [comment]
Can you add a docs page for Boston Housing dataset? That's missing in https://juliaml.github.io/MLDatasets.jl/latest/
