### ISSUE TITLE
MNIST.convert2features() gives DimensionMismatch error

### ISSUE THREAD

**Issue by milanhej** [JuliaML/MLDatasets.jl#40]
The command found on the package documentation 

MNIST.convert2features(MNIST.traintensor())

now produces the error 

┌ Warning: `convert2features` is deprecated, use `reshape` instead.
│   caller = top-level scope at In[7]:1
└ @ Core In[7]:1
DimensionMismatch("parent has 47040000 elements, which is incompatible with size ()")

Using Julia 1.4

Thanks

**Comment by CarloLucibello** [comment]
`convert2features` has been deprecated. Use 
```julia
x = MNIST.traintensor()
reshape(x, 28*28, :)
```
or, for a general tensor x
``` 
reshape(x, :, size(x)[end])
```

**Comment by johnnychen94** [comment]
The docs CI isn't triggered recently due to the unrelated failing test on windows and/or macOS platforms, thus I temporarily disabled the windows test in b88e959 to make sure test passes.

**Comment by johnnychen94** [comment]
@Evizero Can you set up the `DOCUMENTER_KEY` variable for docs CI?

```julia
Initialized empty Git repository in /tmp/jl_J8K6ys/.git/
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
┌ Error: Git failed to fetch git@github.com:JuliaML/MLDatasets.jl.git
│ This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
│ Make sure that the environment variable is properly set up as a Base64-encoded string
│ of the SSH private key. You may need to re-generate the keys with DocumenterTools.
└ @ Documenter ~/.julia/packages/Documenter/QQWIJ/src/Documenter.jl:499
```

**Comment by milanhej** [comment]
Thanks much. All well now.

**Comment by CarloLucibello** [comment]
I think this can be closed
