### ISSUE TITLE
Table not formatted in documentation page. 

### ISSUE THREAD

**Issue by natema** [JuliaML/MLDatasets.jl#43]
The table in the [Data Size section of the documentation](https://juliaml.github.io/MLDatasets.jl/latest/#Data-Size-1) doesn't appear correctly formatted (even though it gets correctly formatted when [previewing the markdown on GitHub](https://github.com/JuliaML/MLDatasets.jl/blob/master/docs/src/index.md)).

**Comment by CarloLucibello** [comment]
the table has been removed in one of the latests PRs
