### ISSUE TITLE
Add option to override interactive prompting

### ISSUE THREAD

**Issue by ablaom** [JuliaML/MLDatasets.jl#63]
```julia
julia> MNIST.traindata()
This program has requested access to the data dependency MNIST.
which is not currently installed. It can be installed automatically, and you will not see this message again.

Do you want to download the dataset from ["https://ossci-datasets.s3.amazonaws.com/mnist/train-images-idx3-ubyte.gz", "https://ossci-datasets.s3.amazonaws.com/mnist/train-labels-idx1-ubyte.gz", "https://ossci-datasets.s3.amazonaws.com/mnist/t10k-images-idx3-ubyte.gz", "https://ossci-datasets.s3.amazonaws.com/mnist/t10k-labels-idx1-ubyte.gz"] to "/Users/anthony/.julia/datadeps/MNIST"?
[y/n]
```

This kind of interactive behaviour can be a headache when loading data in an automated setting, as one does not know ahead of time if a prompt is going to be requested or not. See for example, this issue:

https://github.com/FluxML/MLJFlux.jl/pull/141#issuecomment-845701489

Could we perhaps have an optional kwarg, as in `MNIST.training_data(force=true)`? 

Or is there already a way to do this?

**Comment by ablaom** [comment]
cc @ayush-1506

**Comment by johnnychen94** [comment]
There are two ways to disable interactive prompting:

1. pre-download with `download(; i_accept_the_terms_of_use=true)`.

```julia
MNIST.download(; i_accept_the_terms_of_use=true)
MNIST.traindata()
```

2. set environment variable `DATADEPS_ALWAYS_ACCEPT`

```julia
ENV["DATADEPS_ALWAYS_ACCEPT"] = true
MNIST.traindata()
```

https://github.com/JuliaML/MLDatasets.jl/blob/4b472b90da2ebd41252e6a8b6acf262ff48038f3/src/MNIST/MNIST.jl#L55-L68

**Comment by ablaom** [comment]
Thanks!!
