### ISSUE TITLE
Segmentation fault with Images

### ISSUE THREAD

**Issue by myrddin89** [JuliaML/MLDatasets.jl#64]
I do not know if this issue is related to MLDatasets or Images, but trying to `using MLDatasets, Images` results in segmentation fault for me.

Package versions (Julia 1.6.0):

```
Images v0.24.1
MLDatasets v0.5.6
```

**Comment by johnnychen94** [comment]
It's very likely that you're having a broken installation of packages. Can you try a clean build? For example, start julia with `JULIA_DEPOT_PATH=tmp_depot julia --startup=no`, install MLDatasets and Images, and try it again.

If the issue still occurs, please also report `versioninfo()` and the way you installed Julia.

**Comment by myrddin89** [comment]
Yes, my bad, with a clean build it works fine. I had probably incompatible versions of some packages installed. Thanks for the trouble!
