### ISSUE TITLE
Publish to METADATA

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaML/MLDatasets.jl#7]
Hi,
this package seems useful, in good shape, and also easy to mantain. Is there something preventing official release?

**Comment by Evizero** [comment]
Personally I'd say two things should happen first (which I plan on doing eventually)

- [ ] more formal testing (similar to MNIST submodule)
- [ ] adding an "agreement" dialogue to the other dataset download functions (also in spirit of the MNIST submodule)

**Comment by CarloLucibello** [comment]
The second point could be addressed having a common download utility for all the modules, maybe with a signature like this
```julia
download_helper(baseurl, files; i_accept_the_terms_of_use = false, prompt_info = nothing)
```
where for MNIST for example
```julia
prompt_info = """
Dataset: THE MNIST DATABASE of handwritten digits
Authors: Yann LeCun, Corinna Cortes, Christopher J.C. Burges
Website: http://yann.lecun.com/exdb/mnist/

[LeCun et al., 1998a]
  Y. LeCun, L. Bottou, Y. Bengio, and P. Haffner. 
"Gradient-based learning applied to document recognition." 
Proceedings of the IEEE, 86(11):2278-2324, November 1998
"""
```

**Comment by CarloLucibello** [comment]
maybe the package can just be published now and things improved later. I find the package very handy. It is a pity it's not just a Pkg.add  away, this refrains people from using it

**Comment by rdeits** [comment]
Any updates on this? [MNIST.jl](https://github.com/johnmyleswhite/MNIST.jl) appears abandoned and will be broken in v0.7/1.0 because it still hasn't updated its `Array` constructor syntax. That will mean that `Flux.jl`'s MNIST demo will be broken on 1.0, which might be a hindrance for new users.

**Comment by Evizero** [comment]
I have plans to get this ready for metadata over new years

**Comment by rdeits** [comment]
Awesome, thank you!

**Comment by amellnik** [comment]
See also https://github.com/FluxML/model-zoo/issues/15

**Comment by Evizero** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/13399
