### ISSUE TITLE
documentation failed to the deploy

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaML/MLDatasets.jl#72]
@johnnychen94 last commit failed to deploy the docs
https://github.com/JuliaML/MLDatasets.jl/runs/3172885457
Something is wrong with the DOCUMENTER_KEY, do you know how to fix it?

**Comment by johnnychen94** [comment]
My fault, it seems that I mistakenly copied the

```text
-----BEGIN OPENSSH PRIVATE KEY-----
-----END OPENSSH PRIVATE KEY-----
```

part to the secret.

I also noticed that `gh-page` branch becomes a mass:

```julia
┌ Warning: removing `stable` and linking `stable` to `v0.1.0`.
└ @ Documenter ~/.julia/packages/Documenter/R2HVS/src/Documenter.jl:707
┌ Warning: removing `v0.1` and linking `v0.1` to `v0.1.0`.
└ @ Documenter ~/.julia/packages/Documenter/R2HVS/src/Documenter.jl:707
```

This looks quite strange, so I cleaned it and pushed a new v0.5.9 tag so as to retrigger the documented build. It now should work. https://juliaml.github.io/MLDatasets.jl/stable/ points to v0.5.9 now.

**Comment by CarloLucibello** [comment]
hurrah! thanks
