### ISSUE TITLE
All links to datasets documentation in the home page are broken

### ISSUE THREAD

**Issue by sylvaticus** [JuliaML/MLDatasets.jl#74]
All links in the "datasets" section of the home page (that should point to the specific dataset documentation) are broken (404 not found error), e.g. https://juliaml.github.io/MLDatasets.jl/latest/datasets/MNIST/

**Comment by johnnychen94** [comment]
Mind opening a PR for it?

```diff
- https://juliaml.github.io/MLDatasets.jl/latest/datasets/MNIST/
+ https://juliaml.github.io/MLDatasets.jl/dev/datasets/MNIST/
```

**Comment by sylvaticus** [comment]
Done (as commented in the PR I do believe however that the documentation by default should point to the stable branch)
