### ISSUE TITLE
add Titanic dataset

### ISSUE THREAD

**Issue by arcAman07** [JuliaML/MLDatasets.jl#90]
One of the most famous dataset for a beginner to start is the "Titanic dataset" , which is used for Exploratory data analysis and prediction of outcome using logistic regression, Decision trees, random forests, etc. I just think this dataset should be added so that can be easy for a beginner to get started in Machine learning in julia with a beginner friendly dataset. Also if approved, I am willing to work on this issue as it can be a great addition to these other famous datasets.

**Comment by CarloLucibello** [comment]
Agreed, a pull request would be welcome. You can take as reference the [Iris](https://github.com/JuliaML/MLDatasets.jl/blob/master/src/Iris/Iris.jl) dataset

**Comment by arcAman07** [comment]
Thanks a lot for a quick feedback. Will refer the above iris dataset and will sent the PR in a couple of days after adding the dataset and testing the functionality.

**Comment by arcAman07** [comment]
I will be sending today the pull request for the dataset by adding the test and src codes. If accepted then I can add the documentation after its merged
