### ISSUE TITLE
Not able to load the Titanic Dataset

### ISSUE THREAD

**Issue by arcAman07** [JuliaML/MLDatasets.jl#95]
After adding the Titanic Dataset I am not able to fully load the dataset for use.

**Comment by ToucheSir** [comment]
Can you provide more details on how it's unusable? At the very least a full stacktrace of any errors you run into.

**Comment by arcAman07** [comment]
![image](https://user-images.githubusercontent.com/76823502/154810029-d32a65f4-18be-4a49-9797-42506246fa5c.png)

This is the current error which I am getting ( not with any of the other datasets )

**Comment by ToucheSir** [comment]
I just checked locally and both work. Are you on the latest version (0.5.15)?

**Comment by arcAman07** [comment]
Sorry my bad, issue sorted . I thought I was using the latest version but it was an old one. 
Sorry for the inconvenience.
